language: node_js
node_js:
  - node
install:
  - npm install
deploy:
  provider: heroku
  api_key:
    secure: ZgNwJPQCFFUgsTMSqROSQOFWIgP4jO04h1qkCgPe7YCeIjqvsOGnKyYrJQBHD73msR0YPskpWx8KVBnU7KZhl0+U5FdDCBG2MYs+G4spL3VVVw0fZqd9G9LhZzP9+wOw1/BWF3Q4eeUtW3O3yGg1RrBIBRkEN4p6lt48j3HPdV7LA0oH6eas/BlLXC/AI+Bo/wajhRiYL6kvG527VP0La+WTOM1fwpsLP7TV8gMs6Yf6KZCbnMUj/vyL3wiufV+Og46F3AovLt1jMp6Vfts5YdBfFSKU8Cvdigc5UZ8O4vXuxyGAuyyPojJOU5/s9Br7+a+EzZjIwRCGh/bhPtXn/aPf8EzE+t3GDiw9RlLEosBXtmIT7mX7UpBJXCPMKNJ4KeDZp/2Fjybu/JOj52/ChL1E8a0kftnQvVsSIYNlXhSSgh15ZZ10QSBrktvvqREx/0zRtetudLZLlPHjNKMThMFz3+OZnqJUllKK3c/Ly3S6h26I3ok+2naKqQgdrlraWixNa6/SljI6A6GlcIH/yUOAXpY3GvnpW6AUdKNxlKICzVozmVtHMzC+H9I1BCGDOSRkSjPJgI7B98Sh0ULaReY4VCd12U54MkqY2zMHNE3cSMhrvsJr6OT12wCn0WIOi/PfJJrCat+PQSAL5xF5w9L7ljFT8oOCwDw1MNgFVXk=
